<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HMECL003091" ignored="0" name="Page-Run." tests="3" failures="3" timestamp="09 Apr 2020 07:47:30 GMT" time="6.489" errors="0">
  <testcase name="login" time="2.034" classname="com.qa.tests.FreeCRMAccountPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.tests.FreeCRMAccountPageTest.login(FreeCRMAccountPageTest.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="2.008" classname="com.qa.tests.FreeCRMAccountPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.tests.FreeCRMAccountPageTest.login(FreeCRMAccountPageTest.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="2.009" classname="com.qa.tests.FreeCRMAccountPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.tests.FreeCRMAccountPageTest.login(FreeCRMAccountPageTest.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Page-Run. -->
